Make LineParameterization non-templated
For MSVC, instantiating a dllimport class template will cause error C2491:
definition of dllimport function not allowed.

Change-Id: Icc7f7ea84598df0a5436f48ffc2bab5cfab93921