Update patch set 1
Patch Set 1:

Hi Alex,
While building a project that uses Ceres I got a Werror=unused-parameter that caused my build to fail due to treating all warnings as errors and decided that the simplest solution would be to fix it at the source to avoid future problems for me and anyone else using ceres.

"include/ceres/rotation.h:418:51: error: unused parameter ‘row_stride_parameter’ [-Werror=unused-parameter]"

Patch-set: 1
Reviewer: Gerrit User 5155 <5155@cdcfcfbe-2044-3b1f-b5d4-da77ad542329>
Reviewer: Gerrit User 6160 <6160@cdcfcfbe-2044-3b1f-b5d4-da77ad542329>