Fix compile bug on RHEL6 due to missing header
Fixes compilation error: ‘lower_bound’ was not declared in this scope

Change-Id: I00a32edbb3f7f52c1d09ca4c1ef5ec48692b7748