Improve to residual evaluation error reporting
This substantially improves the error message that is
generated when a user-supplied cost function supplies
invalid data. This issue comes up on the list often, and it
appears the current error message is insufficient. This
change improves the quality of the error message and also
gives more specific details about where the problems are.

Example report
==============
ERROR: Ceres found a bug in your user-supplied cost function:

- You did not fill in all the residuals returned from your cost function
- You did not fill in all the jacobians returned from your cost function

User-supplied cost funtions must do the following:

  (1) Fill in all residual elements with finite values
  (2) If jacobians == NULL, you are done (Ceres is not asking for jacobians)
  (3) Otherwise, Ceres is asking for the jacobians of at least some parameters
  (4) For each jacobians[i] != NULL (if jacobians[i] == NULL, it's constant)
  (5)   Fill in all jacobian values for parameter i with finite values

If you are seeing this error, your cost function is either producing non-finite
values (infs or NaNs) or is not filling in all the values. Ceres pre-fills
arrays with a sentinel value (kImpossibleValue in the Ceres source) to detect
when you have not filled in all the values in either the residuals or jacobians.

If you are using Ceres' autodiff implementation, then it is likely either (a)
residual values are causing the problems or (b) some part of the autodiff
evaluation has bad numeric behaviour. Take a look at ceres/rotation.h for
example code showing special case handling of functions in autodiff.

Which residual block is this? For architecture reasons at this point Ceres
cannot easily identify the block but here is the block's size information:

  Input: 2 parameter blocks; sizes: (9, 3)
  Output: 2 residuals

Problem exists in: User-returned residual values (r[N])

  r[ 0] = 1.0000e+302         ERROR: Value was not set by cost function
  r[ 1] = 1.0000e+302         ERROR: Value was not set by cost function

Problem exists in: User-returned jacobian values d r[N] / d p[M][Q]
where  r[N] is residual element N
       p[M][Q] is parameter M, element Q
       d r[N] / d p[M][Q] is the derivative of the residual w.r.t. the parameter

  Jacobian values for parameter block 0 (p[0][...]):
  d r[ 0] / d p[ 0][ 0] = 7.5087e+01          OK
  d r[ 0] / d p[ 0][ 1] = 2.8426e+02          OK
  d r[ 0] / d p[ 0][ 2] = 5.2498e+02          OK
  d r[ 0] / d p[ 0][ 3] = 1.3239e+01          OK
  d r[ 0] / d p[ 0][ 4] = -6.3351e-08         OK
  d r[ 0] / d p[ 0][ 5] = -1.6646e+00         OK
  d r[ 0] / d p[ 0][ 6] = -1.2573e-01         OK
  d r[ 0] / d p[ 0][ 7] = -1.5024e+01         OK
  d r[ 0] / d p[ 0][ 8] = -1.2536e+00         OK
  d r[ 1] / d p[ 0][ 0] = 1.0000e+302         ERROR: Value was not set by cost function
  d r[ 1] / d p[ 0][ 1] = 1.0000e+302         ERROR: Value was not set by cost function
  d r[ 1] / d p[ 0][ 2] = 1.0000e+302         ERROR: Value was not set by cost function
  d r[ 1] / d p[ 0][ 3] = 1.0000e+302         ERROR: Value was not set by cost function
  d r[ 1] / d p[ 0][ 4] = 1.0000e+302         ERROR: Value was not set by cost function
  d r[ 1] / d p[ 0][ 5] = 1.0000e+302         ERROR: Value was not set by cost function
  d r[ 1] / d p[ 0][ 6] = 1.0000e+302         ERROR: Value was not set by cost function
  d r[ 1] / d p[ 0][ 7] = 1.0000e+302         ERROR: Value was not set by cost function
  d r[ 1] / d p[ 0][ 8] = 1.0000e+302         ERROR: Value was not set by cost function

  Jacobian values for parameter block 1 (p[1][...]):
  d r[ 0] / d p[ 1][ 0] = 1.2155e+01          OK
  d r[ 0] / d p[ 1][ 1] = 3.7116e+00          OK
  d r[ 0] / d p[ 1][ 2] = -4.0662e+00         OK
  d r[ 1] / d p[ 1][ 0] = 1.0000e+302         ERROR: Value was not set by cost function
  d r[ 1] / d p[ 1][ 1] = 1.0000e+302         ERROR: Value was not set by cost function
  d r[ 1] / d p[ 1][ 2] = 1.0000e+302         ERROR: Value was not set by cost function

Change-Id: Icfa5829d701a7298c973235d4e0660c8dc0e3454