Fixed MSVC error C2124: divide or mod by zero
Alternatively, if quiet_NaN is not available on all platforms a workaround would be:
    volatile double zero = 0.0;
    double x = 1.0/zero;
The 'volatile' is needed to shut up "warning C4723: potential divide by 0".

Change-Id: If2bbdab8540595aa2e0079e1eb6b6fed6d4a6ef7