Don't export class template LineParameterization
For MSVC, instantiating a dllimport class template will cause error C2491:
definition of dllimport function not allowed.

Change-Id: I2fddaee6bcc15a3196caf28f3786cd8daf996d1d