Update patch set 3
Patch Set 3:

(1 comment)

This now includes tests, and uses the proper glog and gflags upstream. However, for some reason Eigen is not getting included correctly in the tests. I am not sure why the dependency is not getting picked up for the test macros.

This test fails to build:

% bazel build tiny_solver_cost_function_adapter_test
INFO: Analysed target //:tiny_solver_cost_function_adapter_test (0 packages loaded).
INFO: Found 1 target...
ERROR: /usr/local/google/home/keir/wrk/ceres-solver/BUILD:330:2: C++ compilation of rule '//:tiny_solver_cost_function_adapter_test' failed (Exit 1)
In file included from internal/ceres/tiny_solver_cost_function_adapter_test.cc:31:0:
include/ceres/tiny_solver_cost_function_adapter.h:35:22: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
                      ^
compilation terminated.
Target //:tiny_solver_cost_function_adapter_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.374s, Critical Path: 0.15s
FAILED: Build did NOT complete successfully

This test works fine:

% bazel build program_test                          
INFO: Analysed target //:program_test (0 packages loaded).
INFO: Found 1 target...
Target //:program_test up-to-date:
  bazel-bin/program_test
INFO: Elapsed time: 0.230s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action

The Eigen includes must be working correctly for Ceres, since it includes Eigen. So I am not sure what is going on with the test dependency on Eigen.

Patch-set: 3
Reviewer: Gerrit User 5005 <5005@cdcfcfbe-2044-3b1f-b5d4-da77ad542329>