Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> (2 comments)
> 
> > Patch Set 3:
> > 
> > (2 comments)
> > 
> > Emil,
> > I am still not convinced that floor and trunc should be added to Jets. In fact one of the reasons why ceres ships with the cubic interpolation objects is because doing interpolation in an autodiff friendly way is non-trivial. And in fact the user should NOT be doing linear interpolation because it is not smooth on the vertices.
> 
> I tried removing trunc/round and push a new change-set, but I don't grok gerrit at all. When pushing git told me to pull first, so I did, but I still can't push my changes:
> 
>      ! [remote rejected] HEAD -> master (prohibited by Gerrit: ref update access denied)
>     error: failed to push some refs to 'https://ceres-solver.googlesource.com/ceres-solver'

you want to use git commit --amend when commiting your changes locally, so it is to the same commit ID.

I think you should be able to squash the commit to fix the state of things now?

Patch-set: 3
Reviewer: Gerrit User 5002 <5002@cdcfcfbe-2044-3b1f-b5d4-da77ad542329>